name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - workflow

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: List Files After Build
        run: ls -la

      - name: List Files in dist
        run: ls -la dist

      - name: Check pwd
        run: pwd

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Set up the gh-pages branch
          git fetch origin gh-pages || echo "gh-pages branch not found, will create it"
          git checkout --orphan gh-pages || git checkout gh-pages

          # Remove existing files in the branch (clean slate)
          git rm -rf . || echo "No files to remove"

          # Copy the built assets from temp-deploy
          cp -r ./dist/* .

          # Add .nojekyll to prevent Jekyll processing
          touch .nojekyll

          # Add, commit, and push changes
          git add .
          git commit -m "Deploy to GitHub Pages - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git gh-pages